using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Events;

[Serializable] public class SpriteEvent : UnityEvent<Sprite> {}

public class CommandProcessor : MonoBehaviour
{
    [SerializeField] private CommandInputSystem commandInputSystem;
    [SerializeField] private CommandOutputSystem commandOutputSystem;
    [SerializeField] private ImageRegistry imageRegistry;
    [SerializeField] private TextAsset startingFileSystemJson;
    
    private LinuxCommand _linuxCommand;

    // private VirtualFileSystem _vfs;
    private Dictionary<string, Action<string[]>> _commands = new();
    private string _result;

    public UnityEvent<string> onCommandProcessed;
    // public SpriteEvent onImageOpened; // UI subscribes to this to show images

    private void Awake()
    {
        _linuxCommand = new LinuxCommand(startingFileSystemJson);
        _commands = _linuxCommand.GetCommandList;
        
    //     _vfs = new VirtualFileSystem();
    //     _vfs.LoadFromJson(startingFileSystemJson.text);
    //
    //     _commands = new Dictionary<string, Action<string[]>>
    //     {
    //         { "ls", CmdLs },
    //         { "cd", CmdCd },
    //         { "cat", CmdCat },
    //         { "pwd", args => Print(_vfs.GetCurrentPathString()) },
    //         { "clear", args => _result = "" },
    //         { "whoami", args => Print("user") },
    //         { "help", args => Print(string.Join(", ", _commands.Keys)) },
    //     };
    }

    private void OnEnable()
    {
        _result = GetHeader();
        commandInputSystem.OnCommandSubmitted.AddListener(ProcessCommand);
    }

    private void OnDisable()
    {
        commandInputSystem.OnCommandSubmitted.RemoveListener(ProcessCommand);
    }

    private string GetHeader() => $"user@localhost > {_linuxCommand.GetCurrentPathString()}\n$ ";

    private void ProcessCommand(string command)
    {
        _result += command + "\n";

        var trimmed = command.Trim();
        if (!string.IsNullOrEmpty(trimmed))
        {
            var parts = trimmed.Split(' ', 2);
            var cmd = parts[0].ToLower();
            var args = parts.Length > 1
                ? parts[1].Split(' ', StringSplitOptions.RemoveEmptyEntries)
                : Array.Empty<string>();

            if (_commands.TryGetValue(cmd, out var handler))
            {
                // Execute Linux command
                handler(args);

                // Get the output generated by LinuxCommand
                string commandResult = _linuxCommand.GetResult();

                if (!string.IsNullOrEmpty(commandResult))
                {
                    _result += commandResult;

                    // Clear LinuxCommand's temporary result
                    _linuxCommand.ClearResult();
                }
            }
            else
                Print($"{cmd}: command not found");
        }

        _result += GetHeader();
        onCommandProcessed?.Invoke(_result);
    }

    private void Print(string text) => _result += text + "\n";
    //
    // private void CmdLs(string[] args)
    // {
    //     if (_vfs.CurrentDir.Children.Count == 0) { Print("(empty)"); return; }
    //     Print(string.Join("  ", _vfs.CurrentDir.Children
    //         .Select(c => c.IsDirectory ? c.Name + "/" : c.Name)));
    // }
    //
    // private void CmdCd(string[] args)
    // {
    //     var path = args.Length > 0 ? args[0] : "/";
    //     if (!_vfs.ChangeDirectory(path, out var error)) Print(error);
    // }
    //
    // private void CmdCat(string[] args)
    // {
    //     if (args.Length == 0) { Print("cat: missing filename"); return; }
    //
    //     var node = _vfs.ResolvePath(args[0]);
    //     if (node == null) { Print($"cat: {args[0]}: No such file or directory"); return; }
    //     if (node.IsDirectory) { Print($"cat: {args[0]}: Is a directory"); return; }
    //
    //     if (node.Type == "image")
    //     {
    //         var sprite = imageRegistry.GetImage(node.AssetKey);
    //         if (sprite != null)
    //         {
    //             onImageOpened?.Invoke(sprite);
    //             Print($"[opened image: {node.Name}]");
    //         }
    //         else Print($"cat: could not load image data for {node.Name}");
    //     }
    //     else
    //     {
    //         Print(node.Content);
    //     }
    // }
}